-- Migration 047: Fix encoding for document_sections and field_definitions
-- The seed in migration 044 was stored with wrong encoding (UTF-8 bytes as Latin-1)
-- This migration corrects all name_ru / label_ru values

-- Fix document_sections
UPDATE public.document_sections SET name_ru = 'Жалобы и Анамнез' WHERE code = 'complaints_and_history';
UPDATE public.document_sections SET name_ru = 'Физикальные показатели' WHERE code = 'vitals';
UPDATE public.document_sections SET name_ru = 'Объективная оценка' WHERE code = 'objective_assessment_full';
UPDATE public.document_sections SET name_ru = 'Нутриционный скрининг' WHERE code = 'nutritional_screening';
UPDATE public.document_sections SET name_ru = 'Локальный статус' WHERE code = 'local_status';
UPDATE public.document_sections SET name_ru = 'Диагноз' WHERE code = 'diagnosis';
UPDATE public.document_sections SET name_ru = 'План лечения' WHERE code = 'treatment_plan';
UPDATE public.document_sections SET name_ru = 'План выписки' WHERE code = 'discharge_plan';
UPDATE public.document_sections SET name_ru = 'План операции' WHERE code = 'surgical_plan';
UPDATE public.document_sections SET name_ru = 'Проведённые вмешательства' WHERE code = 'procedures_performed';
UPDATE public.document_sections SET name_ru = 'Участники' WHERE code = 'participants';
UPDATE public.document_sections SET name_ru = 'Верификация' WHERE code = 'verification_checklist';
UPDATE public.document_sections SET name_ru = 'Заключение' WHERE code = 'conclusion';
UPDATE public.document_sections SET name_ru = 'Критерии перевода' WHERE code = 'transfer_criteria_scores';
UPDATE public.document_sections SET name_ru = 'Данные перфузии' WHERE code = 'perfusion_data';
UPDATE public.document_sections SET name_ru = 'М-режим' WHERE code = 'echo_m_mode';
UPDATE public.document_sections SET name_ru = 'В-режим' WHERE code = 'echo_b_mode';
UPDATE public.document_sections SET name_ru = 'Допплерография' WHERE code = 'echo_doppler';
UPDATE public.document_sections SET name_ru = 'Данные УЗИ' WHERE code = 'uzi_findings';
UPDATE public.document_sections SET name_ru = 'Данные ЭКГ' WHERE code = 'ecg_findings';
UPDATE public.document_sections SET name_ru = 'Дневниковая запись' WHERE code = 'daily_note_main';

-- Fix field_definitions
UPDATE public.field_definitions SET label_ru = 'Жалобы' WHERE attribute_code = 'history.complaints';
UPDATE public.field_definitions SET label_ru = 'Анамнез морби' WHERE attribute_code = 'history.anamnesis_morbi';
UPDATE public.field_definitions SET label_ru = 'Аллергия' WHERE attribute_code = 'history.allergies';
UPDATE public.field_definitions SET label_ru = 'Перенесённые заболевания' WHERE attribute_code = 'history.past_illnesses';
UPDATE public.field_definitions SET label_ru = 'Эпидемиологический анамнез / переливание крови' WHERE attribute_code = 'history.epidemiology';
UPDATE public.field_definitions SET label_ru = 'Перенесённые операции' WHERE attribute_code = 'history.past_surgeries';
UPDATE public.field_definitions SET label_ru = 'Лекарственный анамнез' WHERE attribute_code = 'history.medication_history';
UPDATE public.field_definitions SET label_ru = 'Социальный анамнез' WHERE attribute_code = 'history.social_history';
UPDATE public.field_definitions SET label_ru = 'Артериальное давление' WHERE attribute_code = 'vitals.bp';
UPDATE public.field_definitions SET label_ru = 'Пульс' WHERE attribute_code = 'vitals.pulse';
UPDATE public.field_definitions SET label_ru = 'ЧСС' WHERE attribute_code = 'vitals.heart_rate';
UPDATE public.field_definitions SET label_ru = 'Частота дыхания' WHERE attribute_code = 'vitals.rr';
UPDATE public.field_definitions SET label_ru = 'Сатурация SpO2' WHERE attribute_code = 'vitals.spo2';
UPDATE public.field_definitions SET label_ru = 'Температура тела' WHERE attribute_code = 'vitals.temperature';
UPDATE public.field_definitions SET label_ru = 'Рост' WHERE attribute_code = 'vitals.height';
UPDATE public.field_definitions SET label_ru = 'Вес' WHERE attribute_code = 'vitals.weight';
UPDATE public.field_definitions SET label_ru = 'ИМТ' WHERE attribute_code = 'vitals.bmi';
UPDATE public.field_definitions SET label_ru = 'Центральное венозное давление' WHERE attribute_code = 'vitals.cvp';
UPDATE public.field_definitions SET label_ru = 'Время осмотра пациента' WHERE attribute_code = 'vitals.exam_time';
UPDATE public.field_definitions SET label_ru = 'Общее состояние' WHERE attribute_code = 'obj.general';
UPDATE public.field_definitions SET label_ru = 'Объективная оценка' WHERE attribute_code = 'obj.objective';
UPDATE public.field_definitions SET label_ru = 'Кожа' WHERE attribute_code = 'obj.skin';
UPDATE public.field_definitions SET label_ru = 'Сердечно-сосудистая система' WHERE attribute_code = 'obj.cv';
UPDATE public.field_definitions SET label_ru = 'Респираторная система' WHERE attribute_code = 'obj.resp';
UPDATE public.field_definitions SET label_ru = 'Опорно-двигательная система' WHERE attribute_code = 'obj.musculoskeletal';
UPDATE public.field_definitions SET label_ru = 'Мочеполовая система' WHERE attribute_code = 'obj.gu';
UPDATE public.field_definitions SET label_ru = 'Пищеварительная система' WHERE attribute_code = 'obj.gi';
UPDATE public.field_definitions SET label_ru = 'Неврологическая система' WHERE attribute_code = 'obj.neuro';
UPDATE public.field_definitions SET label_ru = 'Локальный статус' WHERE attribute_code = 'obj.local_status';
UPDATE public.field_definitions SET label_ru = 'Депрессия' WHERE attribute_code = 'psych.depression';
UPDATE public.field_definitions SET label_ru = 'Взволнованность / Тревога' WHERE attribute_code = 'psych.anxiety';
UPDATE public.field_definitions SET label_ru = 'Нарушение рационального мышления' WHERE attribute_code = 'psych.thought_disorder';
UPDATE public.field_definitions SET label_ru = 'Недостаток социальной поддержки' WHERE attribute_code = 'psych.social_support';
UPDATE public.field_definitions SET label_ru = 'Негативные мысли' WHERE attribute_code = 'psych.negative_thoughts';
UPDATE public.field_definitions SET label_ru = 'Оценка общего психического состояния' WHERE attribute_code = 'psych.mental_assessment';
UPDATE public.field_definitions SET label_ru = 'Риск самоповреждения' WHERE attribute_code = 'psych.self_harm_risk';
UPDATE public.field_definitions SET label_ru = 'Патология' WHERE attribute_code = 'psych.pathology';
UPDATE public.field_definitions SET label_ru = 'Потеря веса за последние 3 месяца' WHERE attribute_code = 'nutri.weight_loss_3m';
UPDATE public.field_definitions SET label_ru = 'Снижение приёма пищи за последний месяц' WHERE attribute_code = 'nutri.intake_reduction';
UPDATE public.field_definitions SET label_ru = 'Стрессовый фактор / тяжесть заболевания' WHERE attribute_code = 'nutri.stress_factor';
UPDATE public.field_definitions SET label_ru = 'Общий балл' WHERE attribute_code = 'nutri.total_score';
UPDATE public.field_definitions SET label_ru = 'Основной диагноз' WHERE attribute_code = 'diag.main';
UPDATE public.field_definitions SET label_ru = 'Осложнение основного диагноза' WHERE attribute_code = 'diag.complication';
UPDATE public.field_definitions SET label_ru = 'Конкурирующий диагноз' WHERE attribute_code = 'diag.competing';
UPDATE public.field_definitions SET label_ru = 'Фоновый диагноз' WHERE attribute_code = 'diag.background';
UPDATE public.field_definitions SET label_ru = 'Сопутствующий диагноз' WHERE attribute_code = 'diag.concomitant';
UPDATE public.field_definitions SET label_ru = 'Предоперационный диагноз (МКБ-10)' WHERE attribute_code = 'diag.preop';
UPDATE public.field_definitions SET label_ru = 'Постоперационный диагноз (МКБ-10)' WHERE attribute_code = 'diag.postop';
UPDATE public.field_definitions SET label_ru = 'Предварительный диагноз' WHERE attribute_code = 'diag.preliminary';
UPDATE public.field_definitions SET label_ru = 'План лечения' WHERE attribute_code = 'tx.plan';
UPDATE public.field_definitions SET label_ru = 'При госпитализации проверено' WHERE attribute_code = 'tx.admission_check';
UPDATE public.field_definitions SET label_ru = 'Цели госпитализации' WHERE attribute_code = 'tx.goals';
UPDATE public.field_definitions SET label_ru = 'Лабораторная диагностика' WHERE attribute_code = 'tx.lab_diagnostics';
UPDATE public.field_definitions SET label_ru = 'Консультация специалиста' WHERE attribute_code = 'tx.specialist_consult';
UPDATE public.field_definitions SET label_ru = 'Медикаментозные назначения' WHERE attribute_code = 'tx.prescription';
UPDATE public.field_definitions SET label_ru = 'Рекомендации' WHERE attribute_code = 'tx.recommendations';
UPDATE public.field_definitions SET label_ru = 'Диета' WHERE attribute_code = 'tx.diet';
UPDATE public.field_definitions SET label_ru = 'Специальная диета' WHERE attribute_code = 'tx.special_diet';
UPDATE public.field_definitions SET label_ru = 'В динамике общее состояние пациента' WHERE attribute_code = 'dc.dynamics';
UPDATE public.field_definitions SET label_ru = 'Общее состояние при выписке' WHERE attribute_code = 'dc.general_condition';
UPDATE public.field_definitions SET label_ru = 'Тревожные признаки' WHERE attribute_code = 'dc.warning_signs';
UPDATE public.field_definitions SET label_ru = 'Дата следующего визита' WHERE attribute_code = 'dc.follow_up_date';
UPDATE public.field_definitions SET label_ru = 'Где продолжить лечение после выписки' WHERE attribute_code = 'dc.continue_treatment';
UPDATE public.field_definitions SET label_ru = 'Дата поступления' WHERE attribute_code = 'dc.admission_date';
UPDATE public.field_definitions SET label_ru = 'Дата выписки' WHERE attribute_code = 'dc.discharge_date';
UPDATE public.field_definitions SET label_ru = 'Количество койко-дней' WHERE attribute_code = 'dc.bed_days';
UPDATE public.field_definitions SET label_ru = 'Медикаментозные назначения (проведённые)' WHERE attribute_code = 'dc.performed_meds';
UPDATE public.field_definitions SET label_ru = 'Проведённая операция' WHERE attribute_code = 'dc.performed_surgery';
UPDATE public.field_definitions SET label_ru = 'Проведённые лечения, лаб. и инстр. исследования' WHERE attribute_code = 'dc.performed_treatment';
UPDATE public.field_definitions SET label_ru = 'Дата и время перевода' WHERE attribute_code = 'transfer.datetime';
UPDATE public.field_definitions SET label_ru = 'Отделение куда переводится пациент' WHERE attribute_code = 'transfer.destination';
UPDATE public.field_definitions SET label_ru = 'Сдавший врач' WHERE attribute_code = 'transfer.handing_dr';
UPDATE public.field_definitions SET label_ru = 'Принимающий врач' WHERE attribute_code = 'transfer.receiving_dr';
UPDATE public.field_definitions SET label_ru = 'Срочность операции' WHERE attribute_code = 'surg.urgency';
UPDATE public.field_definitions SET label_ru = 'Повторная операция или осложнение' WHERE attribute_code = 'surg.is_repeat';
UPDATE public.field_definitions SET label_ru = 'Операционный блок' WHERE attribute_code = 'surg.operating_block';
UPDATE public.field_definitions SET label_ru = 'Тип анестезии' WHERE attribute_code = 'surg.anesthesia_type';
UPDATE public.field_definitions SET label_ru = 'Дата и время начала операции' WHERE attribute_code = 'surg.start_datetime';
UPDATE public.field_definitions SET label_ru = 'Дата и время окончания операции' WHERE attribute_code = 'surg.end_datetime';
UPDATE public.field_definitions SET label_ru = 'Название операции' WHERE attribute_code = 'surg.operation_name';
UPDATE public.field_definitions SET label_ru = 'Ход операции / процедуры' WHERE attribute_code = 'surg.procedure_course';
UPDATE public.field_definitions SET label_ru = 'Осложнения' WHERE attribute_code = 'surg.complications';
UPDATE public.field_definitions SET label_ru = 'Объём кровопотери (мл)' WHERE attribute_code = 'surg.blood_loss';
UPDATE public.field_definitions SET label_ru = 'Макроскопический препарат' WHERE attribute_code = 'surg.macroscopic';
UPDATE public.field_definitions SET label_ru = 'Классификация хирургического разреза' WHERE attribute_code = 'surg.incision_class';
UPDATE public.field_definitions SET label_ru = 'Дренаж' WHERE attribute_code = 'surg.drainage';
UPDATE public.field_definitions SET label_ru = 'Послеоперационное ведение' WHERE attribute_code = 'surg.postop_management';
UPDATE public.field_definitions SET label_ru = 'Номер протокола операции' WHERE attribute_code = 'surg.protocol_number';
UPDATE public.field_definitions SET label_ru = 'Показание к операции' WHERE attribute_code = 'surg.indication';
UPDATE public.field_definitions SET label_ru = 'Оперирующий врач' WHERE attribute_code = 'part.surgeon';
UPDATE public.field_definitions SET label_ru = 'Первый ассистент' WHERE attribute_code = 'part.assistant_1';
UPDATE public.field_definitions SET label_ru = 'Второй ассистент' WHERE attribute_code = 'part.assistant_2';
UPDATE public.field_definitions SET label_ru = 'Операционная медсестра' WHERE attribute_code = 'part.scrub_nurse';
UPDATE public.field_definitions SET label_ru = 'Анестезиолог' WHERE attribute_code = 'part.anesthesiologist';
UPDATE public.field_definitions SET label_ru = 'Анестезистка' WHERE attribute_code = 'part.anesthesia_nurse';
UPDATE public.field_definitions SET label_ru = 'Дополнительный участник' WHERE attribute_code = 'part.additional';
UPDATE public.field_definitions SET label_ru = 'Приглашённый специалист' WHERE attribute_code = 'part.invited_specialist';
UPDATE public.field_definitions SET label_ru = 'Главный врач' WHERE attribute_code = 'part.chief_physician';
UPDATE public.field_definitions SET label_ru = 'Заведующий отделением' WHERE attribute_code = 'part.dept_head';
UPDATE public.field_definitions SET label_ru = 'Перфузиолог' WHERE attribute_code = 'part.perfusionist';
UPDATE public.field_definitions SET label_ru = 'Перфузистка' WHERE attribute_code = 'part.perfusion_nurse';
UPDATE public.field_definitions SET label_ru = 'Рентген-лаборант' WHERE attribute_code = 'part.radiology_tech';
UPDATE public.field_definitions SET label_ru = 'Принимающий врач' WHERE attribute_code = 'part.receiving_dr';
UPDATE public.field_definitions SET label_ru = 'Сдавший врач' WHERE attribute_code = 'part.handing_dr';
UPDATE public.field_definitions SET label_ru = 'Дата и время начала анестезии' WHERE attribute_code = 'anest.start_datetime';
UPDATE public.field_definitions SET label_ru = 'Дата и время окончания анестезии' WHERE attribute_code = 'anest.end_datetime';
UPDATE public.field_definitions SET label_ru = 'Описание анестезии' WHERE attribute_code = 'anest.description';
UPDATE public.field_definitions SET label_ru = 'Побочные эффекты анестезии' WHERE attribute_code = 'anest.side_effects';
UPDATE public.field_definitions SET label_ru = 'Состояние при сдаче' WHERE attribute_code = 'anest.handover_state';
UPDATE public.field_definitions SET label_ru = 'Шкала ASA' WHERE attribute_code = 'anest.asa_class';
UPDATE public.field_definitions SET label_ru = 'Тест Маллампати' WHERE attribute_code = 'anest.mallampati';
UPDATE public.field_definitions SET label_ru = 'Инструментальная диагностика' WHERE attribute_code = 'anest.instrumental_diag';
UPDATE public.field_definitions SET label_ru = 'Консультации специалистов' WHERE attribute_code = 'anest.consult';
UPDATE public.field_definitions SET label_ru = 'Описание перфузии' WHERE attribute_code = 'perf.description';
UPDATE public.field_definitions SET label_ru = 'Вес' WHERE attribute_code = 'perf.weight';
UPDATE public.field_definitions SET label_ru = 'Рост' WHERE attribute_code = 'perf.height';
UPDATE public.field_definitions SET label_ru = 'Площадь поверхности тела' WHERE attribute_code = 'perf.body_surface_area';
UPDATE public.field_definitions SET label_ru = 'Номер протокола перфузии' WHERE attribute_code = 'perf.protocol_number';
UPDATE public.field_definitions SET label_ru = 'Группа крови и резус-фактор' WHERE attribute_code = 'perf.blood_type';
UPDATE public.field_definitions SET label_ru = 'Артериальная канюля' WHERE attribute_code = 'perf.arterial_cannula';
UPDATE public.field_definitions SET label_ru = 'ВПВ канюля' WHERE attribute_code = 'perf.svc_cannula';
UPDATE public.field_definitions SET label_ru = 'НПВ канюля' WHERE attribute_code = 'perf.ivc_cannula';
UPDATE public.field_definitions SET label_ru = 'Начало перфузии' WHERE attribute_code = 'perf.start_datetime';
UPDATE public.field_definitions SET label_ru = 'Конец перфузии' WHERE attribute_code = 'perf.end_datetime';
UPDATE public.field_definitions SET label_ru = 'Продолжительность перфузии' WHERE attribute_code = 'perf.duration';
UPDATE public.field_definitions SET label_ru = 'Продолжительность ишемии' WHERE attribute_code = 'perf.ischemia_duration';
UPDATE public.field_definitions SET label_ru = 'Объём и скорость перфузии макс' WHERE attribute_code = 'perf.flow_max';
UPDATE public.field_definitions SET label_ru = 'Объём и скорость перфузии мин' WHERE attribute_code = 'perf.flow_min';
UPDATE public.field_definitions SET label_ru = 'Первичный объём заполнения' WHERE attribute_code = 'perf.prime_volume';
UPDATE public.field_definitions SET label_ru = 'ОЦК' WHERE attribute_code = 'perf.cbv';
UPDATE public.field_definitions SET label_ru = 'Баланс крови' WHERE attribute_code = 'perf.blood_balance';
UPDATE public.field_definitions SET label_ru = 'Общий баланс' WHERE attribute_code = 'perf.total_balance';
UPDATE public.field_definitions SET label_ru = 'Гемоглобин' WHERE attribute_code = 'perf.hemoglobin';
UPDATE public.field_definitions SET label_ru = 'Гемотокрит' WHERE attribute_code = 'perf.hematocrit';
UPDATE public.field_definitions SET label_ru = 'Используемое оборудование' WHERE attribute_code = 'perf.equipment';
UPDATE public.field_definitions SET label_ru = 'Цвет кожи и видимых слизистых' WHERE attribute_code = 'tcrit.skin_color';
UPDATE public.field_definitions SET label_ru = 'Дыхание' WHERE attribute_code = 'tcrit.breathing';
UPDATE public.field_definitions SET label_ru = 'Кровообращение' WHERE attribute_code = 'tcrit.circulation';
UPDATE public.field_definitions SET label_ru = 'Сознание' WHERE attribute_code = 'tcrit.consciousness';
UPDATE public.field_definitions SET label_ru = 'Лабораторно-инструментальные показатели' WHERE attribute_code = 'tcrit.lab_findings';
UPDATE public.field_definitions SET label_ru = 'Итого баллов' WHERE attribute_code = 'tcrit.total_score';
UPDATE public.field_definitions SET label_ru = 'Решение о переводе' WHERE attribute_code = 'tcrit.decision';
UPDATE public.field_definitions SET label_ru = 'Комментарий' WHERE attribute_code = 'tcrit.comment';
UPDATE public.field_definitions SET label_ru = 'Зав. отд. ОРИТ' WHERE attribute_code = 'tcrit.icu_head';
UPDATE public.field_definitions SET label_ru = 'Зав. отд. Анестезиологии' WHERE attribute_code = 'tcrit.anest_head';
UPDATE public.field_definitions SET label_ru = 'Идентификация пациента' WHERE attribute_code = 'verif.patient_id';
UPDATE public.field_definitions SET label_ru = 'Название операции (вкратце)' WHERE attribute_code = 'verif.operation_name';
UPDATE public.field_definitions SET label_ru = 'Свежезамороженная плазма' WHERE attribute_code = 'verif.ffp_ordered';
UPDATE public.field_definitions SET label_ru = 'Эритроцитсодержащая трансфузионная среда' WHERE attribute_code = 'verif.rbc_ordered';
UPDATE public.field_definitions SET label_ru = 'Тромбоконцентрат' WHERE attribute_code = 'verif.platelets_ordered';
UPDATE public.field_definitions SET label_ru = 'Имплантируемые устройства заказаны' WHERE attribute_code = 'verif.implants_ordered';
UPDATE public.field_definitions SET label_ru = 'Вид, название, размер имплантата' WHERE attribute_code = 'verif.implant_details';
UPDATE public.field_definitions SET label_ru = 'Выставлен предоперационный диагноз' WHERE attribute_code = 'verif.preop_diagnosis_set';
UPDATE public.field_definitions SET label_ru = 'Получено согласие на операцию' WHERE attribute_code = 'verif.consent_surgery';
UPDATE public.field_definitions SET label_ru = 'Получено согласие на анестезию' WHERE attribute_code = 'verif.consent_anesthesia';
UPDATE public.field_definitions SET label_ru = 'Проведены лабораторные исследования' WHERE attribute_code = 'verif.labs_done';
UPDATE public.field_definitions SET label_ru = 'Проведена ЭКГ' WHERE attribute_code = 'verif.ecg_done';
UPDATE public.field_definitions SET label_ru = 'Проведены рентген/КТ/МРТ' WHERE attribute_code = 'verif.imaging_done';
UPDATE public.field_definitions SET label_ru = 'Проведён осмотр анестезиолога' WHERE attribute_code = 'verif.anest_exam_done';
UPDATE public.field_definitions SET label_ru = 'Определена и подготовлена премедикация' WHERE attribute_code = 'verif.premedication';
UPDATE public.field_definitions SET label_ru = 'Катетеризация центральных вен' WHERE attribute_code = 'verif.cvc';
UPDATE public.field_definitions SET label_ru = 'Максимальная доза контраста (мл)' WHERE attribute_code = 'verif.max_contrast_dose';
UPDATE public.field_definitions SET label_ru = 'Маркировка тела' WHERE attribute_code = 'verif.body_marking';
UPDATE public.field_definitions SET label_ru = 'Язык общения пациента' WHERE attribute_code = 'admit.language';
UPDATE public.field_definitions SET label_ru = 'Триаж' WHERE attribute_code = 'admit.triage';
UPDATE public.field_definitions SET label_ru = 'Риск падения пациента' WHERE attribute_code = 'admit.fall_risk';
UPDATE public.field_definitions SET label_ru = 'Инвалидность' WHERE attribute_code = 'admit.disability';
UPDATE public.field_definitions SET label_ru = 'Пациент жалуется на боль' WHERE attribute_code = 'admit.pain_present';
UPDATE public.field_definitions SET label_ru = 'Оценка боли (0–10)' WHERE attribute_code = 'admit.pain_score';
UPDATE public.field_definitions SET label_ru = 'Скрининг на инфекционную патологию' WHERE attribute_code = 'admit.infection_screening';
UPDATE public.field_definitions SET label_ru = 'Обнаружен педикулёз' WHERE attribute_code = 'admit.pediculosis';
UPDATE public.field_definitions SET label_ru = 'Предварительный диагноз' WHERE attribute_code = 'admit.preliminary_diag';
UPDATE public.field_definitions SET label_ru = 'Решение о госпитализации' WHERE attribute_code = 'admit.decision';
UPDATE public.field_definitions SET label_ru = 'Перевод в другую мед организацию' WHERE attribute_code = 'admit.transfer_org';
UPDATE public.field_definitions SET label_ru = 'Отказ от госпитализации' WHERE attribute_code = 'admit.refusal';
UPDATE public.field_definitions SET label_ru = 'Медсестра приёмного отделения' WHERE attribute_code = 'admit.admitting_nurse';
UPDATE public.field_definitions SET label_ru = 'Заключение' WHERE attribute_code = 'cons.conclusion';
UPDATE public.field_definitions SET label_ru = 'Стратегия хирургического лечения' WHERE attribute_code = 'cons.surg_strategy';
UPDATE public.field_definitions SET label_ru = 'Стратегия анестезиологического обеспечения' WHERE attribute_code = 'cons.anest_strategy';
UPDATE public.field_definitions SET label_ru = 'Стратегия после операции' WHERE attribute_code = 'cons.postop_strategy';
UPDATE public.field_definitions SET label_ru = 'Планирование выписки' WHERE attribute_code = 'cons.discharge_planning';
UPDATE public.field_definitions SET label_ru = 'Участвовали' WHERE attribute_code = 'cons.participants';
UPDATE public.field_definitions SET label_ru = 'Дата и время' WHERE attribute_code = 'cons.datetime';
UPDATE public.field_definitions SET label_ru = 'Номер протокола вмешательства' WHERE attribute_code = 'ir.protocol_number';
UPDATE public.field_definitions SET label_ru = 'Название процедуры' WHERE attribute_code = 'ir.procedure_name';
UPDATE public.field_definitions SET label_ru = 'Место пункции' WHERE attribute_code = 'ir.puncture_site';
UPDATE public.field_definitions SET label_ru = 'Заключение' WHERE attribute_code = 'ir.conclusion';
UPDATE public.field_definitions SET label_ru = 'Показание к операции' WHERE attribute_code = 'preop.indication';
UPDATE public.field_definitions SET label_ru = 'Название операции' WHERE attribute_code = 'preop.operation_name';
UPDATE public.field_definitions SET label_ru = 'Время операции' WHERE attribute_code = 'preop.surgery_time';
UPDATE public.field_definitions SET label_ru = 'Тактика и объём операции' WHERE attribute_code = 'preop.surgery_plan';
UPDATE public.field_definitions SET label_ru = 'Ожидаемые технические сложности' WHERE attribute_code = 'preop.technical_difficulties';
UPDATE public.field_definitions SET label_ru = 'Вероятные послеоперационные осложнения' WHERE attribute_code = 'preop.postop_complications';
UPDATE public.field_definitions SET label_ru = 'Профилактика постоперационных осложнений' WHERE attribute_code = 'preop.complication_prevention';
UPDATE public.field_definitions SET label_ru = 'Тип обезболивания' WHERE attribute_code = 'preop.anesthesia_type';
UPDATE public.field_definitions SET label_ru = 'Ожидаемый объём кровопотери' WHERE attribute_code = 'preop.expected_blood_loss';
UPDATE public.field_definitions SET label_ru = 'ЧСС (уд/мин)' WHERE attribute_code = 'echo.heart_rate';
UPDATE public.field_definitions SET label_ru = 'Аорта (Ao)' WHERE attribute_code = 'echo.aorta';
UPDATE public.field_definitions SET label_ru = 'Левое предсердие (LA)' WHERE attribute_code = 'echo.left_atrium';
UPDATE public.field_definitions SET label_ru = 'Аортальный клапан' WHERE attribute_code = 'echo.aortic_valve';
UPDATE public.field_definitions SET label_ru = 'Митральный клапан' WHERE attribute_code = 'echo.mitral_valve';
UPDATE public.field_definitions SET label_ru = 'Правый желудочек' WHERE attribute_code = 'echo.right_ventricle';
UPDATE public.field_definitions SET label_ru = 'МЖП (IVS)' WHERE attribute_code = 'echo.ivs';
UPDATE public.field_definitions SET label_ru = 'КДР (EDD) см' WHERE attribute_code = 'echo.lv_edd';
UPDATE public.field_definitions SET label_ru = 'КСР (ESD) см' WHERE attribute_code = 'echo.lv_esd';
UPDATE public.field_definitions SET label_ru = 'ФВ (EF) %' WHERE attribute_code = 'echo.ef';
UPDATE public.field_definitions SET label_ru = 'ФУ (FS) %' WHERE attribute_code = 'echo.fs';
UPDATE public.field_definitions SET label_ru = 'ЗСЛЖ (LVMD) см' WHERE attribute_code = 'echo.lv_posterior_wall';
UPDATE public.field_definitions SET label_ru = 'КДО (EDV) мл' WHERE attribute_code = 'echo.edv';
UPDATE public.field_definitions SET label_ru = 'КСО (ESV) мл' WHERE attribute_code = 'echo.esv';
UPDATE public.field_definitions SET label_ru = 'УО (SV) мл' WHERE attribute_code = 'echo.sv';
UPDATE public.field_definitions SET label_ru = 'ММЛЖ (MW) г' WHERE attribute_code = 'echo.lv_mass';
UPDATE public.field_definitions SET label_ru = 'ИММЛЖ (MI) г/м²' WHERE attribute_code = 'echo.lv_mass_index';
UPDATE public.field_definitions SET label_ru = 'Митральный клапан (Доплер)' WHERE attribute_code = 'echo.doppler_mitral';
UPDATE public.field_definitions SET label_ru = 'Трёхстворчатый клапан' WHERE attribute_code = 'echo.doppler_tricuspid';
UPDATE public.field_definitions SET label_ru = 'Аорта (Доплер)' WHERE attribute_code = 'echo.doppler_aorta';
UPDATE public.field_definitions SET label_ru = 'Лёгочная артерия (Доплер)' WHERE attribute_code = 'echo.doppler_pulmonary';
UPDATE public.field_definitions SET label_ru = 'Систолическое давление в ПЖ' WHERE attribute_code = 'echo.rvsp';
UPDATE public.field_definitions SET label_ru = 'Описание' WHERE attribute_code = 'echo.description';
UPDATE public.field_definitions SET label_ru = 'Заключение' WHERE attribute_code = 'echo.conclusion';
UPDATE public.field_definitions SET label_ru = 'Ритм сердца' WHERE attribute_code = 'ecg.rhythm';
UPDATE public.field_definitions SET label_ru = 'Описание' WHERE attribute_code = 'ecg.description';
UPDATE public.field_definitions SET label_ru = 'Заключение' WHERE attribute_code = 'ecg.conclusion';
UPDATE public.field_definitions SET label_ru = 'Печень' WHERE attribute_code = 'uzi.liver';
UPDATE public.field_definitions SET label_ru = 'Желчный пузырь' WHERE attribute_code = 'uzi.gallbladder';
UPDATE public.field_definitions SET label_ru = 'Поджелудочная железа' WHERE attribute_code = 'uzi.pancreas';
UPDATE public.field_definitions SET label_ru = 'Селезёнка' WHERE attribute_code = 'uzi.spleen';
UPDATE public.field_definitions SET label_ru = 'Правая почка' WHERE attribute_code = 'uzi.right_kidney';
UPDATE public.field_definitions SET label_ru = 'Левая почка' WHERE attribute_code = 'uzi.left_kidney';
UPDATE public.field_definitions SET label_ru = 'Матка' WHERE attribute_code = 'uzi.uterus';
UPDATE public.field_definitions SET label_ru = 'Шейка матки' WHERE attribute_code = 'uzi.cervix';
UPDATE public.field_definitions SET label_ru = 'Яичники' WHERE attribute_code = 'uzi.ovaries';
UPDATE public.field_definitions SET label_ru = 'Мочевой пузырь' WHERE attribute_code = 'uzi.bladder';
UPDATE public.field_definitions SET label_ru = 'Предстательная железа' WHERE attribute_code = 'uzi.prostate';
UPDATE public.field_definitions SET label_ru = 'Описание' WHERE attribute_code = 'uzi.description';
UPDATE public.field_definitions SET label_ru = 'Заключение' WHERE attribute_code = 'uzi.conclusion';
UPDATE public.field_definitions SET label_ru = 'Аллергия' WHERE attribute_code = 'daily.allergy';
UPDATE public.field_definitions SET label_ru = 'Общее состояние' WHERE attribute_code = 'daily.general_condition';
UPDATE public.field_definitions SET label_ru = 'Осложнение основного диагноза' WHERE attribute_code = 'daily.diag_complication';
UPDATE public.field_definitions SET label_ru = 'Сопутствующий диагноз' WHERE attribute_code = 'daily.concomitant';
UPDATE public.field_definitions SET label_ru = 'План лечения' WHERE attribute_code = 'daily.treatment_plan';
